name: pytorch1.0
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.5
  - pytorch=1.0.0
  - torchvision
  - numpy
  - nltk
  - ipython
  - docopt
  - pip:
    - tqdm
    - slacker
    - ipdb
    - msgpack
    - sumeval
    - tensorboardX
    - torch